### ISSUE TITLE
formulaire pour créer une  communauté

### ISSUE THREAD

**Issue by Leoglme** [Leoglme/tauri-reddit-mobile-app#11]

**Comment by LaGeogeoTeam** [comment]
28/02/2023 16:19:51 - creation of the 11-formulaire-pour-crer-une-communaut branch and branch link to issue 11 -

**Comment by LaGeogeoTeam** [comment]
06/03/2023 15:12:05 - create pull request branch   11-formulaire-pour-crer-une-communaut to preprod -
