### ISSUE TITLE
profil de la communauté

### ISSUE THREAD

**Issue by Leoglme** [Leoglme/tauri-reddit-mobile-app#16]
Le strict minimum est d'afficher le nom, le titre, le numéro de

abonnés, description et image d'en-tête

**Comment by LaGeogeoTeam** [comment]
28/02/2023 12:11:39 - creation of the 16-profil-de-la-communaut branch and branch link to issue 16 -

**Comment by LaGeogeoTeam** [comment]
28/02/2023 16:18:26 - create pull request branch   16-profil-de-la-communaut to preprod -
