### ISSUE TITLE
lister tous les posts des communauté auxquels l'utilisateur est abonné sur la page accueil

### ISSUE THREAD

**Issue by Leoglme** [Leoglme/tauri-reddit-mobile-app#19]

**Comment by LaGeogeoTeam** [comment]
27/02/2023 12:55:17 - creation of the 19-lister-tous-les-posts-des-communaut-auxquels-lutilisateur-est-abonn-sur-la-page-accueil branch and branch link to issue 19 -

**Comment by LaGeogeoTeam** [comment]
28/02/2023 12:11:08 - create pull request branch   19-lister-tous-les-posts-des-communaut-auxquels-lutilisateur-est-abonn-sur-la-page-accueil to preprod -
