### ISSUE TITLE
component select filtre communauté

### ISSUE THREAD

**Issue by Leoglme** [Leoglme/tauri-reddit-mobile-app#22]
le filtre est à mettre sur la page accueil et la page profil de la communauté

![Image](https://user-images.githubusercontent.com/74193170/218433278-9b45dda4-dca3-4c19-a945-6d9df6f7b4da.png)

**Comment by LaGeogeoTeam** [comment]
06/03/2023 16:00:11 - creation of the 22-component-select-filtre-communaut branch and branch link to issue 22 -

**Comment by LaGeogeoTeam** [comment]
07/03/2023 11:57:44 - create pull request branch   22-component-select-filtre-communaut to preprod -
