### ISSUE TITLE
mise en place de vitest

### ISSUE THREAD

**Issue by Leoglme** [Leoglme/tauri-reddit-mobile-app#6]

**Comment by LaGeogeoTeam** [comment]
21/02/2023 17:00:11 - creation of the 6-mise-en-place-de-vitest branch and branch link to issue 6 -

**Comment by LaGeogeoTeam** [comment]
21/02/2023 17:00:51 - creation of the 6-mise-en-place-de-vitest branch and branch link to issue 6 -
